#!/bin/bash
sudo apt update
sudo apt install xrdp
sudo adduser xrdp ssl-cert
sudo ufw allow 3389/tcp
sudo adduser xrdp ssl-cert
sudo systemctl restart xrdp
sudo usermod -a -G ssl-cert xrdp
sudo systemctl restart xrdp
